In [1]:
from cnn-error-analysis import cifar10
from cnn-error-analysis import data_analysis as da
from cnn-error-analysis import visualization as vis
from cnn-error-analysis import evaluation as ev

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# set paths to stored extracted features
fv_test_url = "D:/tmp/inceptionV1_finetuned_cifar10_version9/ckpt_204365_extracted/InceptionV1_CifarTest_fv.csv"
logits_test_url = "D:/tmp/inceptionV1_finetuned_cifar10_version9/ckpt_204365_extracted/InceptionV1_CifarTest_logits.csv"

fv_train_url = "D:/tmp/inceptionV1_finetuned_cifar10_version9/ckpt_204365_extracted/InceptionV1_CifarTrain_fv.csv"
logits_train_url = "D:/tmp/inceptionV1_finetuned_cifar10_version9/ckpt_204365_extracted/InceptionV1_CifarTrain_logits.csv"

In [3]:
#current_analysis_folder = "E:/OneDrive/DiplomNotebooks/Skripte_Dokumentation/analysis/"
#current_class = "60k"

In [4]:
# load the data: Test Set
cifar_test_fv_df = cifar10.load_csv_into_df(fv_test_url)
cifar_test_logits_df = cifar10.load_csv_into_df(logits_test_url)
#Train Set
cifar_train_fv_df = cifar10.load_csv_into_df(fv_train_url)
cifar_train_logits_df = cifar10.load_csv_into_df(logits_train_url)

#concat
fv_df = pd.concat([cifar_test_fv_df, cifar_train_fv_df])
logits_df = pd.concat([cifar_test_logits_df, cifar_train_logits_df])
# predict and label column in logits df
logits_df = cifar10.add_predicted_classnr_column(logits_df)
logits_df = cifar10.add_true_classnr_column(logits_df)
logits_df.head(n=3)

#reset index
fv_df = fv_df.reset_index(drop=True)
logits_df = logits_df.reset_index(drop=True)

#slice
#x_fv_df = cifar10.slice_df_by_classes(fv_df,[current_class])
#x_logits_df = cifar10.slice_df_by_classes(logits_df,[current_class])

In [7]:
logits_df.head()

,image,out0,out1,out2,out3,out4,out5,out6,out7,out8,out9,prediction,true_label
0,cat0,-5.142417,-1.729621,-0.969845,17.364624,-5.808441,1.824337,1.528700,-3.433535,-2.691775,-4.383957,3,3
1,ship1,1.410706,4.041996,-2.879023,-3.667110,-3.824167,-2.193284,-3.336461,-3.021400,14.498526,-2.634876,8,8
2,ship2,-2.962451,3.798997,-1.335378,-3.004028,-2.824133,-1.654863,-3.081724,-0.954745,11.418835,-0.006088,8,8
3,airplane3,12.985446,-1.701919,-0.319613,-2.024185,-3.208709,-4.358646,-1.225058,-1.911954,2.187253,-2.800862,0,0
4,frog4,-3.493262,-0.592864,-1.832079,-1.930654,1.207956,-3.417982,17.134953,-4.277920,-1.479361,-1.612655,6,6

In [8]:
fv_df.head()

,image,n0,n1,n2,n3,n4,n5,n6,n7,n8,...,n1014,n1015,n1016,n1017,n1018,n1019,n1020,n1021,n1022,n1023
0,cat0,0.088050,1.519237,0.175741,0.190639,0.615950,0.002988,0.376658,0.573202,0.060558,...,0.200374,0.118481,0.257751,0.718142,0.021241,0.028894,0.773978,0.834805,1.276739,0.000000
1,ship1,0.144110,0.003399,0.415825,0.439820,0.293926,0.296895,0.484401,0.207155,0.419569,...,0.031579,0.000000,0.205622,1.180065,0.365335,0.734212,0.191780,0.133029,0.000000,0.022964
2,ship2,0.058279,0.009433,0.184899,0.462435,0.077979,0.664359,0.191462,0.333204,0.359889,...,0.000000,0.028630,0.442743,1.215681,0.249046,0.723484,0.119448,0.063178,0.000000,0.094399
3,airplane3,0.507074,0.054394,0.932945,0.219226,0.353469,0.022414,0.883811,0.139136,0.095787,...,0.584027,0.021427,0.622056,0.420828,0.554128,0.054255,0.433157,0.305606,0.524276,0.000000
4,frog4,0.231066,1.118897,0.045164,1.341475,0.000000,0.000000,0.599749,0.683527,1.387691,...,0.002975,1.682296,0.000000,0.119046,0.003866,0.093303,0.040250,0.807730,0.856685,0.016978

## KPIS

KPIs Functions

In [ ]:
# takes a lot of time, compute once and save as csv
#distances, indices = nearest_neighbors(fv_df, neighbors=20)
#pd.DataFrame(indices).to_csv(current_analysis_folder + "nn_indices.csv")
#pd.DataFrame(distances).to_csv(current_analysis_folder + "distances.csv")

In [5]:
#load distances
nn_matrix = pd.read_csv(current_analysis_folder + "nn_indices.csv", sep=',', low_memory=False, error_bad_lines=False,header=None,skiprows=[0],index_col=0)

In [6]:
conf_per_class_all, conf_own_all, ttc_all, min_sm_all = ev.calculate_all_kpis(nn_matrix.to_numpy(),fv_df,logits_df)

current class - > airplane
df shape (6000, 1025)
df shape (6000, 13)
class_testimages_indices len 1000
current class - > automobile
df shape (6000, 1025)
df shape (6000, 13)
class_testimages_indices len 1000
current class - > bird
df shape (6000, 1025)
df shape (6000, 13)
class_testimages_indices len 1000
current class - > cat
df shape (6000, 1025)
df shape (6000, 13)
class_testimages_indices len 1000
current class - > deer
df shape (6000, 1025)
df shape (6000, 13)
class_testimages_indices len 1000
current class - > dog
df shape (6000, 1025)
df shape (6000, 13)
class_testimages_indices len 1000
current class - > frog
df shape (6000, 1025)
df shape (6000, 13)
class_testimages_indices len 1000
current class - > horse
df shape (6000, 1025)
df shape (6000, 13)
class_testimages_indices len 1000
current class - > ship
df shape (6000, 1025)
df shape (6000, 13)
class_testimages_indices len 1000
current class - > truck
df shape (6000, 1025)
df shape (6000, 13)
class_testimages_indices len 1000
condfidence_per_class=  [[0.9914249916917858, 0.0003164136476957615, 0.0017472296664212713, 0.0006368370097246252, 0.00033563336453515543, 0.00018783096298558295, 0.0002223281589255182, 0.00048016686810242016, 0.0038982726843247873, 0.0007502959454992293], [0.0005066204601796804, 0.9951341934530916, 0.00016241123129882336, 3.433275080927404e-05, 0.0001553188239806871, 7.706352224172072e-06, 0.00012829413760336714, 0.0003415047997250503, 0.0009000567660851463, 0.002629561225002284], [0.002669721210571967, 9.460371426570352e-05, 0.9866997896923267, 0.0016458171035110113, 0.0027900379390475615, 0.002326857966169445, 0.0026830365338087084, 0.0006105024675151072, 0.0003232141070607693, 0.0001564192657229745], [0.001196448405342745, 0.0007696274429409071, 0.0027961611617513256, 0.9798408509672583, 0.0025640579944507117, 0.007402391209264408, 0.002968537343497169, 0.0019655557897919917, 0.0003215179029714064, 0.0001748517827311102], [0.0007691504127777008, 2.8631946588364286e-05, 0.0015568319032061811, 0.0018760686563471772, 0.9917932964997705, 0.0010239100052826672, 0.0006335127247711404, 0.0017170989882715646, 0.0005456537573889361, 5.5845105595805806e-05], [0.00020325012011524236, 0.0003768226004299859, 0.0006311107700099981, 0.005452917077696669, 0.0009508607070208777, 0.9877953840916587, 0.001622171830243705, 0.002861236115905256, 2.289874092256007e-05, 8.334794599696803e-05], [0.00020972333725381278, 6.627931376709707e-05, 0.0006814928380822827, 0.002628488740816311, 0.0005401978271024376, 0.0005404259860165581, 0.9949132590763157, 0.00032049782278692463, 8.299372161738923e-05, 1.6641336241381962e-05], [0.0005257307401535161, 2.3800549752993792e-05, 0.0006145761663727947, 0.0014524123357804925, 0.0010210705020535012, 0.0010013687085205292, 0.0002007299566266552, 0.9949882538069891, 0.00013625613355379724, 3.5801100196668025e-05], [0.003024251003511992, 0.001042587285987987, 0.00020696444921634302, 0.0004644423760768211, 1.9875357588376483e-05, 2.0740114095913715e-05, 0.00018078994303210504, 0.00015045287088691074, 0.9937502872809572, 0.0011396093186462628], [0.0006277314257759169, 0.004066782016145416, 3.4841614707581746e-05, 0.00015604005609070457, 1.1133746317227697e-05, 2.8385815190930218e-05, 0.0005230619211633704, 0.0001134208113143582, 0.0014207602544128975, 0.9930178423388817]]
confidence_own_class=  [0.9914249916917858, 0.9951341934530916, 0.9866997896923267, 0.9798408509672583, 0.9917932964997705, 0.9877953840916587, 0.9949132590763157, 0.9949882538069891, 0.9937502872809572, 0.9930178423388817]
ttc=  [14.793, 15.064, 14.133, 12.858, 14.631, 13.378, 15.204, 14.987, 15.104, 14.634]

In [7]:
for i in range(0,10):
    print(conf_own_all[i])

0.9914249916917858
0.9951341934530916
0.9866997896923267
0.9798408509672583
0.9917932964997705
0.9877953840916587
0.9949132590763157
0.9949882538069891
0.9937502872809572
0.9930178423388817

In [9]:
 ttc_all

[14.793,
 15.064,
 14.133,
 12.858,
 14.631,
 13.378,
 15.204,
 14.987,
 15.104,
 14.634]

In [10]:
for i in range(0,10):
    print(ttc_all[i]/16.66)

0.8879351740696279
0.9042016806722689
0.8483193277310924
0.7717887154861945
0.8782112845138055
0.8030012004801921
0.9126050420168067
0.8995798319327731
0.9066026410564225
0.878391356542617